Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_kafka="kafka-secret"
    user_kafka-connect="connect-secret"
    user_schemaregistry="schemaregistry-secret"
    user_kafka-ui="kafka-ui-secret";
}