apiVersion: v1
kind: Secret
metadata:
  name: meridian-event-platform-secrets
  namespace: meridian
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  SPRING_KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"meridian\" password=\"REPLACE_WITH_KAFKA_PASSWORD\";"
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_YOUR_RSA_PUBLIC_KEY
    -----END PUBLIC KEY-----
