server:
  port: 8080
  servlet:
    max-http-header-size: 8KB
    max-http-post-size: 1MB

spring:
  application:
    name: meridian-event-platform
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
